# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/avleen/softwares/libslater

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/avleen/softwares/libslater

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avleen/softwares/libslater/CMakeFiles /home/avleen/softwares/libslater//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avleen/softwares/libslater/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named libslater

# Build rule for target.
libslater: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libslater
.PHONY : libslater

# fast build rule for target.
libslater/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/build
.PHONY : libslater/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named simple2

# Build rule for target.
simple2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple2
.PHONY : simple2

# fast build rule for target.
simple2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple2.dir/build.make CMakeFiles/simple2.dir/build
.PHONY : simple2/fast

#=============================================================================
# Target rules for targets named simple3

# Build rule for target.
simple3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple3
.PHONY : simple3

# fast build rule for target.
simple3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple3.dir/build.make CMakeFiles/simple3.dir/build
.PHONY : simple3/fast

#=============================================================================
# Target rules for targets named simple4c

# Build rule for target.
simple4c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple4c
.PHONY : simple4c

# fast build rule for target.
simple4c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c.dir/build.make CMakeFiles/simple4c.dir/build
.PHONY : simple4c/fast

#=============================================================================
# Target rules for targets named simple4c_any

# Build rule for target.
simple4c_any: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple4c_any
.PHONY : simple4c_any

# fast build rule for target.
simple4c_any/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c_any.dir/build.make CMakeFiles/simple4c_any.dir/build
.PHONY : simple4c_any/fast

#=============================================================================
# Target rules for targets named test3c

# Build rule for target.
test3c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test3c
.PHONY : test3c

# fast build rule for target.
test3c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test3c.dir/build.make CMakeFiles/test3c.dir/build
.PHONY : test3c/fast

#=============================================================================
# Target rules for targets named test4c

# Build rule for target.
test4c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test4c
.PHONY : test4c

# fast build rule for target.
test4c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test4c.dir/build.make CMakeFiles/test4c.dir/build
.PHONY : test4c/fast

#=============================================================================
# Target rules for targets named test-sph-harm

# Build rule for target.
test-sph-harm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-sph-harm
.PHONY : test-sph-harm

# fast build rule for target.
test-sph-harm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-sph-harm.dir/build.make CMakeFiles/test-sph-harm.dir/build
.PHONY : test-sph-harm/fast

#=============================================================================
# Target rules for targets named cleancov

# Build rule for target.
cleancov: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cleancov
.PHONY : cleancov

# fast build rule for target.
cleancov/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleancov.dir/build.make CMakeFiles/cleancov.dir/build
.PHONY : cleancov/fast

#=============================================================================
# Target rules for targets named test-all

# Build rule for target.
test-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-all
.PHONY : test-all

# fast build rule for target.
test-all/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-all.dir/build.make test/CMakeFiles/test-all.dir/build
.PHONY : test-all/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

examples/simple.o: examples/simple.cpp.o
.PHONY : examples/simple.o

# target to build an object file
examples/simple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/examples/simple.cpp.o
.PHONY : examples/simple.cpp.o

examples/simple.i: examples/simple.cpp.i
.PHONY : examples/simple.i

# target to preprocess a source file
examples/simple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/examples/simple.cpp.i
.PHONY : examples/simple.cpp.i

examples/simple.s: examples/simple.cpp.s
.PHONY : examples/simple.s

# target to generate assembly for a file
examples/simple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple.dir/build.make CMakeFiles/simple.dir/examples/simple.cpp.s
.PHONY : examples/simple.cpp.s

examples/simple2.o: examples/simple2.cpp.o
.PHONY : examples/simple2.o

# target to build an object file
examples/simple2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple2.dir/build.make CMakeFiles/simple2.dir/examples/simple2.cpp.o
.PHONY : examples/simple2.cpp.o

examples/simple2.i: examples/simple2.cpp.i
.PHONY : examples/simple2.i

# target to preprocess a source file
examples/simple2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple2.dir/build.make CMakeFiles/simple2.dir/examples/simple2.cpp.i
.PHONY : examples/simple2.cpp.i

examples/simple2.s: examples/simple2.cpp.s
.PHONY : examples/simple2.s

# target to generate assembly for a file
examples/simple2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple2.dir/build.make CMakeFiles/simple2.dir/examples/simple2.cpp.s
.PHONY : examples/simple2.cpp.s

examples/simple3.o: examples/simple3.cpp.o
.PHONY : examples/simple3.o

# target to build an object file
examples/simple3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple3.dir/build.make CMakeFiles/simple3.dir/examples/simple3.cpp.o
.PHONY : examples/simple3.cpp.o

examples/simple3.i: examples/simple3.cpp.i
.PHONY : examples/simple3.i

# target to preprocess a source file
examples/simple3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple3.dir/build.make CMakeFiles/simple3.dir/examples/simple3.cpp.i
.PHONY : examples/simple3.cpp.i

examples/simple3.s: examples/simple3.cpp.s
.PHONY : examples/simple3.s

# target to generate assembly for a file
examples/simple3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple3.dir/build.make CMakeFiles/simple3.dir/examples/simple3.cpp.s
.PHONY : examples/simple3.cpp.s

examples/simple4c.o: examples/simple4c.cpp.o
.PHONY : examples/simple4c.o

# target to build an object file
examples/simple4c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c.dir/build.make CMakeFiles/simple4c.dir/examples/simple4c.cpp.o
.PHONY : examples/simple4c.cpp.o

examples/simple4c.i: examples/simple4c.cpp.i
.PHONY : examples/simple4c.i

# target to preprocess a source file
examples/simple4c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c.dir/build.make CMakeFiles/simple4c.dir/examples/simple4c.cpp.i
.PHONY : examples/simple4c.cpp.i

examples/simple4c.s: examples/simple4c.cpp.s
.PHONY : examples/simple4c.s

# target to generate assembly for a file
examples/simple4c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c.dir/build.make CMakeFiles/simple4c.dir/examples/simple4c.cpp.s
.PHONY : examples/simple4c.cpp.s

examples/simple4c_any.o: examples/simple4c_any.cpp.o
.PHONY : examples/simple4c_any.o

# target to build an object file
examples/simple4c_any.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c_any.dir/build.make CMakeFiles/simple4c_any.dir/examples/simple4c_any.cpp.o
.PHONY : examples/simple4c_any.cpp.o

examples/simple4c_any.i: examples/simple4c_any.cpp.i
.PHONY : examples/simple4c_any.i

# target to preprocess a source file
examples/simple4c_any.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c_any.dir/build.make CMakeFiles/simple4c_any.dir/examples/simple4c_any.cpp.i
.PHONY : examples/simple4c_any.cpp.i

examples/simple4c_any.s: examples/simple4c_any.cpp.s
.PHONY : examples/simple4c_any.s

# target to generate assembly for a file
examples/simple4c_any.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simple4c_any.dir/build.make CMakeFiles/simple4c_any.dir/examples/simple4c_any.cpp.s
.PHONY : examples/simple4c_any.cpp.s

examples/test-sph-harm.o: examples/test-sph-harm.cpp.o
.PHONY : examples/test-sph-harm.o

# target to build an object file
examples/test-sph-harm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-sph-harm.dir/build.make CMakeFiles/test-sph-harm.dir/examples/test-sph-harm.cpp.o
.PHONY : examples/test-sph-harm.cpp.o

examples/test-sph-harm.i: examples/test-sph-harm.cpp.i
.PHONY : examples/test-sph-harm.i

# target to preprocess a source file
examples/test-sph-harm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-sph-harm.dir/build.make CMakeFiles/test-sph-harm.dir/examples/test-sph-harm.cpp.i
.PHONY : examples/test-sph-harm.cpp.i

examples/test-sph-harm.s: examples/test-sph-harm.cpp.s
.PHONY : examples/test-sph-harm.s

# target to generate assembly for a file
examples/test-sph-harm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-sph-harm.dir/build.make CMakeFiles/test-sph-harm.dir/examples/test-sph-harm.cpp.s
.PHONY : examples/test-sph-harm.cpp.s

examples/test3c.o: examples/test3c.cpp.o
.PHONY : examples/test3c.o

# target to build an object file
examples/test3c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test3c.dir/build.make CMakeFiles/test3c.dir/examples/test3c.cpp.o
.PHONY : examples/test3c.cpp.o

examples/test3c.i: examples/test3c.cpp.i
.PHONY : examples/test3c.i

# target to preprocess a source file
examples/test3c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test3c.dir/build.make CMakeFiles/test3c.dir/examples/test3c.cpp.i
.PHONY : examples/test3c.cpp.i

examples/test3c.s: examples/test3c.cpp.s
.PHONY : examples/test3c.s

# target to generate assembly for a file
examples/test3c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test3c.dir/build.make CMakeFiles/test3c.dir/examples/test3c.cpp.s
.PHONY : examples/test3c.cpp.s

examples/test4c.o: examples/test4c.cpp.o
.PHONY : examples/test4c.o

# target to build an object file
examples/test4c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test4c.dir/build.make CMakeFiles/test4c.dir/examples/test4c.cpp.o
.PHONY : examples/test4c.cpp.o

examples/test4c.i: examples/test4c.cpp.i
.PHONY : examples/test4c.i

# target to preprocess a source file
examples/test4c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test4c.dir/build.make CMakeFiles/test4c.dir/examples/test4c.cpp.i
.PHONY : examples/test4c.cpp.i

examples/test4c.s: examples/test4c.cpp.s
.PHONY : examples/test4c.s

# target to generate assembly for a file
examples/test4c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test4c.dir/build.make CMakeFiles/test4c.dir/examples/test4c.cpp.s
.PHONY : examples/test4c.cpp.s

precalculate/gaunt-table.o: precalculate/gaunt-table.cpp.o
.PHONY : precalculate/gaunt-table.o

# target to build an object file
precalculate/gaunt-table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/precalculate/gaunt-table.cpp.o
.PHONY : precalculate/gaunt-table.cpp.o

precalculate/gaunt-table.i: precalculate/gaunt-table.cpp.i
.PHONY : precalculate/gaunt-table.i

# target to preprocess a source file
precalculate/gaunt-table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/precalculate/gaunt-table.cpp.i
.PHONY : precalculate/gaunt-table.cpp.i

precalculate/gaunt-table.s: precalculate/gaunt-table.cpp.s
.PHONY : precalculate/gaunt-table.s

# target to generate assembly for a file
precalculate/gaunt-table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/precalculate/gaunt-table.cpp.s
.PHONY : precalculate/gaunt-table.cpp.s

src/analytical-3c.o: src/analytical-3c.cpp.o
.PHONY : src/analytical-3c.o

# target to build an object file
src/analytical-3c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/analytical-3c.cpp.o
.PHONY : src/analytical-3c.cpp.o

src/analytical-3c.i: src/analytical-3c.cpp.i
.PHONY : src/analytical-3c.i

# target to preprocess a source file
src/analytical-3c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/analytical-3c.cpp.i
.PHONY : src/analytical-3c.cpp.i

src/analytical-3c.s: src/analytical-3c.cpp.s
.PHONY : src/analytical-3c.s

# target to generate assembly for a file
src/analytical-3c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/analytical-3c.cpp.s
.PHONY : src/analytical-3c.cpp.s

src/basis_functions.o: src/basis_functions.cpp.o
.PHONY : src/basis_functions.o

# target to build an object file
src/basis_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/basis_functions.cpp.o
.PHONY : src/basis_functions.cpp.o

src/basis_functions.i: src/basis_functions.cpp.i
.PHONY : src/basis_functions.i

# target to preprocess a source file
src/basis_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/basis_functions.cpp.i
.PHONY : src/basis_functions.cpp.i

src/basis_functions.s: src/basis_functions.cpp.s
.PHONY : src/basis_functions.s

# target to generate assembly for a file
src/basis_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/basis_functions.cpp.s
.PHONY : src/basis_functions.cpp.s

src/bfunctions.o: src/bfunctions.cpp.o
.PHONY : src/bfunctions.o

# target to build an object file
src/bfunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/bfunctions.cpp.o
.PHONY : src/bfunctions.cpp.o

src/bfunctions.i: src/bfunctions.cpp.i
.PHONY : src/bfunctions.i

# target to preprocess a source file
src/bfunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/bfunctions.cpp.i
.PHONY : src/bfunctions.cpp.i

src/bfunctions.s: src/bfunctions.cpp.s
.PHONY : src/bfunctions.s

# target to generate assembly for a file
src/bfunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/bfunctions.cpp.s
.PHONY : src/bfunctions.cpp.s

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/fortran-4c/DFj42.o: src/fortran-4c/DFj42.c.o
.PHONY : src/fortran-4c/DFj42.o

# target to build an object file
src/fortran-4c/DFj42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DFj42.c.o
.PHONY : src/fortran-4c/DFj42.c.o

src/fortran-4c/DFj42.i: src/fortran-4c/DFj42.c.i
.PHONY : src/fortran-4c/DFj42.i

# target to preprocess a source file
src/fortran-4c/DFj42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DFj42.c.i
.PHONY : src/fortran-4c/DFj42.c.i

src/fortran-4c/DFj42.s: src/fortran-4c/DFj42.c.s
.PHONY : src/fortran-4c/DFj42.s

# target to generate assembly for a file
src/fortran-4c/DFj42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DFj42.c.s
.PHONY : src/fortran-4c/DFj42.c.s

src/fortran-4c/DG.o: src/fortran-4c/DG.c.o
.PHONY : src/fortran-4c/DG.o

# target to build an object file
src/fortran-4c/DG.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DG.c.o
.PHONY : src/fortran-4c/DG.c.o

src/fortran-4c/DG.i: src/fortran-4c/DG.c.i
.PHONY : src/fortran-4c/DG.i

# target to preprocess a source file
src/fortran-4c/DG.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DG.c.i
.PHONY : src/fortran-4c/DG.c.i

src/fortran-4c/DG.s: src/fortran-4c/DG.c.s
.PHONY : src/fortran-4c/DG.s

# target to generate assembly for a file
src/fortran-4c/DG.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DG.c.s
.PHONY : src/fortran-4c/DG.c.s

src/fortran-4c/DX.o: src/fortran-4c/DX.c.o
.PHONY : src/fortran-4c/DX.o

# target to build an object file
src/fortran-4c/DX.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DX.c.o
.PHONY : src/fortran-4c/DX.c.o

src/fortran-4c/DX.i: src/fortran-4c/DX.c.i
.PHONY : src/fortran-4c/DX.i

# target to preprocess a source file
src/fortran-4c/DX.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DX.c.i
.PHONY : src/fortran-4c/DX.c.i

src/fortran-4c/DX.s: src/fortran-4c/DX.c.s
.PHONY : src/fortran-4c/DX.s

# target to generate assembly for a file
src/fortran-4c/DX.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/DX.c.s
.PHONY : src/fortran-4c/DX.c.s

src/fortran-4c/Dbsj.o: src/fortran-4c/Dbsj.c.o
.PHONY : src/fortran-4c/Dbsj.o

# target to build an object file
src/fortran-4c/Dbsj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Dbsj.c.o
.PHONY : src/fortran-4c/Dbsj.c.o

src/fortran-4c/Dbsj.i: src/fortran-4c/Dbsj.c.i
.PHONY : src/fortran-4c/Dbsj.i

# target to preprocess a source file
src/fortran-4c/Dbsj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Dbsj.c.i
.PHONY : src/fortran-4c/Dbsj.c.i

src/fortran-4c/Dbsj.s: src/fortran-4c/Dbsj.c.s
.PHONY : src/fortran-4c/Dbsj.s

# target to generate assembly for a file
src/fortran-4c/Dbsj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Dbsj.c.s
.PHONY : src/fortran-4c/Dbsj.c.s

src/fortran-4c/Dtk.o: src/fortran-4c/Dtk.c.o
.PHONY : src/fortran-4c/Dtk.o

# target to build an object file
src/fortran-4c/Dtk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Dtk.c.o
.PHONY : src/fortran-4c/Dtk.c.o

src/fortran-4c/Dtk.i: src/fortran-4c/Dtk.c.i
.PHONY : src/fortran-4c/Dtk.i

# target to preprocess a source file
src/fortran-4c/Dtk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Dtk.c.i
.PHONY : src/fortran-4c/Dtk.c.i

src/fortran-4c/Dtk.s: src/fortran-4c/Dtk.c.s
.PHONY : src/fortran-4c/Dtk.s

# target to generate assembly for a file
src/fortran-4c/Dtk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Dtk.c.s
.PHONY : src/fortran-4c/Dtk.c.s

src/fortran-4c/FSCj.o: src/fortran-4c/FSCj.c.o
.PHONY : src/fortran-4c/FSCj.o

# target to build an object file
src/fortran-4c/FSCj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/FSCj.c.o
.PHONY : src/fortran-4c/FSCj.c.o

src/fortran-4c/FSCj.i: src/fortran-4c/FSCj.c.i
.PHONY : src/fortran-4c/FSCj.i

# target to preprocess a source file
src/fortran-4c/FSCj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/FSCj.c.i
.PHONY : src/fortran-4c/FSCj.c.i

src/fortran-4c/FSCj.s: src/fortran-4c/FSCj.c.s
.PHONY : src/fortran-4c/FSCj.s

# target to generate assembly for a file
src/fortran-4c/FSCj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/FSCj.c.s
.PHONY : src/fortran-4c/FSCj.c.s

src/fortran-4c/Fj42.o: src/fortran-4c/Fj42.c.o
.PHONY : src/fortran-4c/Fj42.o

# target to build an object file
src/fortran-4c/Fj42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Fj42.c.o
.PHONY : src/fortran-4c/Fj42.c.o

src/fortran-4c/Fj42.i: src/fortran-4c/Fj42.c.i
.PHONY : src/fortran-4c/Fj42.i

# target to preprocess a source file
src/fortran-4c/Fj42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Fj42.c.i
.PHONY : src/fortran-4c/Fj42.c.i

src/fortran-4c/Fj42.s: src/fortran-4c/Fj42.c.s
.PHONY : src/fortran-4c/Fj42.s

# target to generate assembly for a file
src/fortran-4c/Fj42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/Fj42.c.s
.PHONY : src/fortran-4c/Fj42.c.s

src/fortran-4c/GREP-WD42.o: src/fortran-4c/GREP-WD42.c.o
.PHONY : src/fortran-4c/GREP-WD42.o

# target to build an object file
src/fortran-4c/GREP-WD42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GREP-WD42.c.o
.PHONY : src/fortran-4c/GREP-WD42.c.o

src/fortran-4c/GREP-WD42.i: src/fortran-4c/GREP-WD42.c.i
.PHONY : src/fortran-4c/GREP-WD42.i

# target to preprocess a source file
src/fortran-4c/GREP-WD42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GREP-WD42.c.i
.PHONY : src/fortran-4c/GREP-WD42.c.i

src/fortran-4c/GREP-WD42.s: src/fortran-4c/GREP-WD42.c.s
.PHONY : src/fortran-4c/GREP-WD42.s

# target to generate assembly for a file
src/fortran-4c/GREP-WD42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GREP-WD42.c.s
.PHONY : src/fortran-4c/GREP-WD42.c.s

src/fortran-4c/GaussLag.o: src/fortran-4c/GaussLag.c.o
.PHONY : src/fortran-4c/GaussLag.o

# target to build an object file
src/fortran-4c/GaussLag.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GaussLag.c.o
.PHONY : src/fortran-4c/GaussLag.c.o

src/fortran-4c/GaussLag.i: src/fortran-4c/GaussLag.c.i
.PHONY : src/fortran-4c/GaussLag.i

# target to preprocess a source file
src/fortran-4c/GaussLag.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GaussLag.c.i
.PHONY : src/fortran-4c/GaussLag.c.i

src/fortran-4c/GaussLag.s: src/fortran-4c/GaussLag.c.s
.PHONY : src/fortran-4c/GaussLag.s

# target to generate assembly for a file
src/fortran-4c/GaussLag.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GaussLag.c.s
.PHONY : src/fortran-4c/GaussLag.c.s

src/fortran-4c/GaussLeg.o: src/fortran-4c/GaussLeg.c.o
.PHONY : src/fortran-4c/GaussLeg.o

# target to build an object file
src/fortran-4c/GaussLeg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GaussLeg.c.o
.PHONY : src/fortran-4c/GaussLeg.c.o

src/fortran-4c/GaussLeg.i: src/fortran-4c/GaussLeg.c.i
.PHONY : src/fortran-4c/GaussLeg.i

# target to preprocess a source file
src/fortran-4c/GaussLeg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GaussLeg.c.i
.PHONY : src/fortran-4c/GaussLeg.c.i

src/fortran-4c/GaussLeg.s: src/fortran-4c/GaussLeg.c.s
.PHONY : src/fortran-4c/GaussLeg.s

# target to generate assembly for a file
src/fortran-4c/GaussLeg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/GaussLeg.c.s
.PHONY : src/fortran-4c/GaussLeg.c.s

src/fortran-4c/HFa42.o: src/fortran-4c/HFa42.c.o
.PHONY : src/fortran-4c/HFa42.o

# target to build an object file
src/fortran-4c/HFa42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/HFa42.c.o
.PHONY : src/fortran-4c/HFa42.c.o

src/fortran-4c/HFa42.i: src/fortran-4c/HFa42.c.i
.PHONY : src/fortran-4c/HFa42.i

# target to preprocess a source file
src/fortran-4c/HFa42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/HFa42.c.i
.PHONY : src/fortran-4c/HFa42.c.i

src/fortran-4c/HFa42.s: src/fortran-4c/HFa42.c.s
.PHONY : src/fortran-4c/HFa42.s

# target to generate assembly for a file
src/fortran-4c/HFa42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/HFa42.c.s
.PHONY : src/fortran-4c/HFa42.c.s

src/fortran-4c/HFj42.o: src/fortran-4c/HFj42.c.o
.PHONY : src/fortran-4c/HFj42.o

# target to build an object file
src/fortran-4c/HFj42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/HFj42.c.o
.PHONY : src/fortran-4c/HFj42.c.o

src/fortran-4c/HFj42.i: src/fortran-4c/HFj42.c.i
.PHONY : src/fortran-4c/HFj42.i

# target to preprocess a source file
src/fortran-4c/HFj42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/HFj42.c.i
.PHONY : src/fortran-4c/HFj42.c.i

src/fortran-4c/HFj42.s: src/fortran-4c/HFj42.c.s
.PHONY : src/fortran-4c/HFj42.s

# target to generate assembly for a file
src/fortran-4c/HFj42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/HFj42.c.s
.PHONY : src/fortran-4c/HFj42.c.s

src/fortran-4c/LU.o: src/fortran-4c/LU.c.o
.PHONY : src/fortran-4c/LU.o

# target to build an object file
src/fortran-4c/LU.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/LU.c.o
.PHONY : src/fortran-4c/LU.c.o

src/fortran-4c/LU.i: src/fortran-4c/LU.c.i
.PHONY : src/fortran-4c/LU.i

# target to preprocess a source file
src/fortran-4c/LU.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/LU.c.i
.PHONY : src/fortran-4c/LU.c.i

src/fortran-4c/LU.s: src/fortran-4c/LU.c.s
.PHONY : src/fortran-4c/LU.s

# target to generate assembly for a file
src/fortran-4c/LU.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/LU.c.s
.PHONY : src/fortran-4c/LU.c.s

src/fortran-4c/bessel_reduite.o: src/fortran-4c/bessel_reduite.c.o
.PHONY : src/fortran-4c/bessel_reduite.o

# target to build an object file
src/fortran-4c/bessel_reduite.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/bessel_reduite.c.o
.PHONY : src/fortran-4c/bessel_reduite.c.o

src/fortran-4c/bessel_reduite.i: src/fortran-4c/bessel_reduite.c.i
.PHONY : src/fortran-4c/bessel_reduite.i

# target to preprocess a source file
src/fortran-4c/bessel_reduite.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/bessel_reduite.c.i
.PHONY : src/fortran-4c/bessel_reduite.c.i

src/fortran-4c/bessel_reduite.s: src/fortran-4c/bessel_reduite.c.s
.PHONY : src/fortran-4c/bessel_reduite.s

# target to generate assembly for a file
src/fortran-4c/bessel_reduite.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/bessel_reduite.c.s
.PHONY : src/fortran-4c/bessel_reduite.c.s

src/fortran-4c/calf42.o: src/fortran-4c/calf42.c.o
.PHONY : src/fortran-4c/calf42.o

# target to build an object file
src/fortran-4c/calf42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/calf42.c.o
.PHONY : src/fortran-4c/calf42.c.o

src/fortran-4c/calf42.i: src/fortran-4c/calf42.c.i
.PHONY : src/fortran-4c/calf42.i

# target to preprocess a source file
src/fortran-4c/calf42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/calf42.c.i
.PHONY : src/fortran-4c/calf42.c.i

src/fortran-4c/calf42.s: src/fortran-4c/calf42.c.s
.PHONY : src/fortran-4c/calf42.s

# target to generate assembly for a file
src/fortran-4c/calf42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/calf42.c.s
.PHONY : src/fortran-4c/calf42.c.s

src/fortran-4c/cartco.o: src/fortran-4c/cartco.c.o
.PHONY : src/fortran-4c/cartco.o

# target to build an object file
src/fortran-4c/cartco.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/cartco.c.o
.PHONY : src/fortran-4c/cartco.c.o

src/fortran-4c/cartco.i: src/fortran-4c/cartco.c.i
.PHONY : src/fortran-4c/cartco.i

# target to preprocess a source file
src/fortran-4c/cartco.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/cartco.c.i
.PHONY : src/fortran-4c/cartco.c.i

src/fortran-4c/cartco.s: src/fortran-4c/cartco.c.s
.PHONY : src/fortran-4c/cartco.s

# target to generate assembly for a file
src/fortran-4c/cartco.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/cartco.c.s
.PHONY : src/fortran-4c/cartco.c.s

src/fortran-4c/coeffbons.o: src/fortran-4c/coeffbons.c.o
.PHONY : src/fortran-4c/coeffbons.o

# target to build an object file
src/fortran-4c/coeffbons.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/coeffbons.c.o
.PHONY : src/fortran-4c/coeffbons.c.o

src/fortran-4c/coeffbons.i: src/fortran-4c/coeffbons.c.i
.PHONY : src/fortran-4c/coeffbons.i

# target to preprocess a source file
src/fortran-4c/coeffbons.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/coeffbons.c.i
.PHONY : src/fortran-4c/coeffbons.c.i

src/fortran-4c/coeffbons.s: src/fortran-4c/coeffbons.c.s
.PHONY : src/fortran-4c/coeffbons.s

# target to generate assembly for a file
src/fortran-4c/coeffbons.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/coeffbons.c.s
.PHONY : src/fortran-4c/coeffbons.c.s

src/fortran-4c/constlmp.o: src/fortran-4c/constlmp.c.o
.PHONY : src/fortran-4c/constlmp.o

# target to build an object file
src/fortran-4c/constlmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/constlmp.c.o
.PHONY : src/fortran-4c/constlmp.c.o

src/fortran-4c/constlmp.i: src/fortran-4c/constlmp.c.i
.PHONY : src/fortran-4c/constlmp.i

# target to preprocess a source file
src/fortran-4c/constlmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/constlmp.c.i
.PHONY : src/fortran-4c/constlmp.c.i

src/fortran-4c/constlmp.s: src/fortran-4c/constlmp.c.s
.PHONY : src/fortran-4c/constlmp.s

# target to generate assembly for a file
src/fortran-4c/constlmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/constlmp.c.s
.PHONY : src/fortran-4c/constlmp.c.s

src/fortran-4c/dobin.o: src/fortran-4c/dobin.c.o
.PHONY : src/fortran-4c/dobin.o

# target to build an object file
src/fortran-4c/dobin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/dobin.c.o
.PHONY : src/fortran-4c/dobin.c.o

src/fortran-4c/dobin.i: src/fortran-4c/dobin.c.i
.PHONY : src/fortran-4c/dobin.i

# target to preprocess a source file
src/fortran-4c/dobin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/dobin.c.i
.PHONY : src/fortran-4c/dobin.c.i

src/fortran-4c/dobin.s: src/fortran-4c/dobin.c.s
.PHONY : src/fortran-4c/dobin.s

# target to generate assembly for a file
src/fortran-4c/dobin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/dobin.c.s
.PHONY : src/fortran-4c/dobin.c.s

src/fortran-4c/fa42.o: src/fortran-4c/fa42.c.o
.PHONY : src/fortran-4c/fa42.o

# target to build an object file
src/fortran-4c/fa42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/fa42.c.o
.PHONY : src/fortran-4c/fa42.c.o

src/fortran-4c/fa42.i: src/fortran-4c/fa42.c.i
.PHONY : src/fortran-4c/fa42.i

# target to preprocess a source file
src/fortran-4c/fa42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/fa42.c.i
.PHONY : src/fortran-4c/fa42.c.i

src/fortran-4c/fa42.s: src/fortran-4c/fa42.c.s
.PHONY : src/fortran-4c/fa42.s

# target to generate assembly for a file
src/fortran-4c/fa42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/fa42.c.s
.PHONY : src/fortran-4c/fa42.c.s

src/fortran-4c/g.o: src/fortran-4c/g.c.o
.PHONY : src/fortran-4c/g.o

# target to build an object file
src/fortran-4c/g.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/g.c.o
.PHONY : src/fortran-4c/g.c.o

src/fortran-4c/g.i: src/fortran-4c/g.c.i
.PHONY : src/fortran-4c/g.i

# target to preprocess a source file
src/fortran-4c/g.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/g.c.i
.PHONY : src/fortran-4c/g.c.i

src/fortran-4c/g.s: src/fortran-4c/g.c.s
.PHONY : src/fortran-4c/g.s

# target to generate assembly for a file
src/fortran-4c/g.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/g.c.s
.PHONY : src/fortran-4c/g.c.s

src/fortran-4c/gaunt.o: src/fortran-4c/gaunt.c.o
.PHONY : src/fortran-4c/gaunt.o

# target to build an object file
src/fortran-4c/gaunt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/gaunt.c.o
.PHONY : src/fortran-4c/gaunt.c.o

src/fortran-4c/gaunt.i: src/fortran-4c/gaunt.c.i
.PHONY : src/fortran-4c/gaunt.i

# target to preprocess a source file
src/fortran-4c/gaunt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/gaunt.c.i
.PHONY : src/fortran-4c/gaunt.c.i

src/fortran-4c/gaunt.s: src/fortran-4c/gaunt.c.s
.PHONY : src/fortran-4c/gaunt.s

# target to generate assembly for a file
src/fortran-4c/gaunt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/gaunt.c.s
.PHONY : src/fortran-4c/gaunt.c.s

src/fortran-4c/gaunt1.o: src/fortran-4c/gaunt1.c.o
.PHONY : src/fortran-4c/gaunt1.o

# target to build an object file
src/fortran-4c/gaunt1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/gaunt1.c.o
.PHONY : src/fortran-4c/gaunt1.c.o

src/fortran-4c/gaunt1.i: src/fortran-4c/gaunt1.c.i
.PHONY : src/fortran-4c/gaunt1.i

# target to preprocess a source file
src/fortran-4c/gaunt1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/gaunt1.c.i
.PHONY : src/fortran-4c/gaunt1.c.i

src/fortran-4c/gaunt1.s: src/fortran-4c/gaunt1.c.s
.PHONY : src/fortran-4c/gaunt1.s

# target to generate assembly for a file
src/fortran-4c/gaunt1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/gaunt1.c.s
.PHONY : src/fortran-4c/gaunt1.c.s

src/fortran-4c/harmonique.o: src/fortran-4c/harmonique.c.o
.PHONY : src/fortran-4c/harmonique.o

# target to build an object file
src/fortran-4c/harmonique.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/harmonique.c.o
.PHONY : src/fortran-4c/harmonique.c.o

src/fortran-4c/harmonique.i: src/fortran-4c/harmonique.c.i
.PHONY : src/fortran-4c/harmonique.i

# target to preprocess a source file
src/fortran-4c/harmonique.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/harmonique.c.i
.PHONY : src/fortran-4c/harmonique.c.i

src/fortran-4c/harmonique.s: src/fortran-4c/harmonique.c.s
.PHONY : src/fortran-4c/harmonique.s

# target to generate assembly for a file
src/fortran-4c/harmonique.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/harmonique.c.s
.PHONY : src/fortran-4c/harmonique.c.s

src/fortran-4c/hatk.o: src/fortran-4c/hatk.c.o
.PHONY : src/fortran-4c/hatk.o

# target to build an object file
src/fortran-4c/hatk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/hatk.c.o
.PHONY : src/fortran-4c/hatk.c.o

src/fortran-4c/hatk.i: src/fortran-4c/hatk.c.i
.PHONY : src/fortran-4c/hatk.i

# target to preprocess a source file
src/fortran-4c/hatk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/hatk.c.i
.PHONY : src/fortran-4c/hatk.c.i

src/fortran-4c/hatk.s: src/fortran-4c/hatk.c.s
.PHONY : src/fortran-4c/hatk.s

# target to generate assembly for a file
src/fortran-4c/hatk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/hatk.c.s
.PHONY : src/fortran-4c/hatk.c.s

src/fortran-4c/legendre.o: src/fortran-4c/legendre.c.o
.PHONY : src/fortran-4c/legendre.o

# target to build an object file
src/fortran-4c/legendre.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/legendre.c.o
.PHONY : src/fortran-4c/legendre.c.o

src/fortran-4c/legendre.i: src/fortran-4c/legendre.c.i
.PHONY : src/fortran-4c/legendre.i

# target to preprocess a source file
src/fortran-4c/legendre.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/legendre.c.i
.PHONY : src/fortran-4c/legendre.c.i

src/fortran-4c/legendre.s: src/fortran-4c/legendre.c.s
.PHONY : src/fortran-4c/legendre.s

# target to generate assembly for a file
src/fortran-4c/legendre.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/legendre.c.s
.PHONY : src/fortran-4c/legendre.c.s

src/fortran-4c/main.o: src/fortran-4c/main.c.o
.PHONY : src/fortran-4c/main.o

# target to build an object file
src/fortran-4c/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/main.c.o
.PHONY : src/fortran-4c/main.c.o

src/fortran-4c/main.i: src/fortran-4c/main.c.i
.PHONY : src/fortran-4c/main.i

# target to preprocess a source file
src/fortran-4c/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/main.c.i
.PHONY : src/fortran-4c/main.c.i

src/fortran-4c/main.s: src/fortran-4c/main.c.s
.PHONY : src/fortran-4c/main.s

# target to generate assembly for a file
src/fortran-4c/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/main.c.s
.PHONY : src/fortran-4c/main.c.s

src/fortran-4c/miscfunc.o: src/fortran-4c/miscfunc.c.o
.PHONY : src/fortran-4c/miscfunc.o

# target to build an object file
src/fortran-4c/miscfunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/miscfunc.c.o
.PHONY : src/fortran-4c/miscfunc.c.o

src/fortran-4c/miscfunc.i: src/fortran-4c/miscfunc.c.i
.PHONY : src/fortran-4c/miscfunc.i

# target to preprocess a source file
src/fortran-4c/miscfunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/miscfunc.c.i
.PHONY : src/fortran-4c/miscfunc.c.i

src/fortran-4c/miscfunc.s: src/fortran-4c/miscfunc.c.s
.PHONY : src/fortran-4c/miscfunc.s

# target to generate assembly for a file
src/fortran-4c/miscfunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/miscfunc.c.s
.PHONY : src/fortran-4c/miscfunc.c.s

src/fortran-4c/msphj.o: src/fortran-4c/msphj.c.o
.PHONY : src/fortran-4c/msphj.o

# target to build an object file
src/fortran-4c/msphj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/msphj.c.o
.PHONY : src/fortran-4c/msphj.c.o

src/fortran-4c/msphj.i: src/fortran-4c/msphj.c.i
.PHONY : src/fortran-4c/msphj.i

# target to preprocess a source file
src/fortran-4c/msphj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/msphj.c.i
.PHONY : src/fortran-4c/msphj.c.i

src/fortran-4c/msphj.s: src/fortran-4c/msphj.c.s
.PHONY : src/fortran-4c/msphj.s

# target to generate assembly for a file
src/fortran-4c/msphj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/msphj.c.s
.PHONY : src/fortran-4c/msphj.c.s

src/fortran-4c/power_x.o: src/fortran-4c/power_x.c.o
.PHONY : src/fortran-4c/power_x.o

# target to build an object file
src/fortran-4c/power_x.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/power_x.c.o
.PHONY : src/fortran-4c/power_x.c.o

src/fortran-4c/power_x.i: src/fortran-4c/power_x.c.i
.PHONY : src/fortran-4c/power_x.i

# target to preprocess a source file
src/fortran-4c/power_x.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/power_x.c.i
.PHONY : src/fortran-4c/power_x.c.i

src/fortran-4c/power_x.s: src/fortran-4c/power_x.c.s
.PHONY : src/fortran-4c/power_x.s

# target to generate assembly for a file
src/fortran-4c/power_x.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/power_x.c.s
.PHONY : src/fortran-4c/power_x.c.s

src/fortran-4c/racdi.o: src/fortran-4c/racdi.c.o
.PHONY : src/fortran-4c/racdi.o

# target to build an object file
src/fortran-4c/racdi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/racdi.c.o
.PHONY : src/fortran-4c/racdi.c.o

src/fortran-4c/racdi.i: src/fortran-4c/racdi.c.i
.PHONY : src/fortran-4c/racdi.i

# target to preprocess a source file
src/fortran-4c/racdi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/racdi.c.i
.PHONY : src/fortran-4c/racdi.c.i

src/fortran-4c/racdi.s: src/fortran-4c/racdi.c.s
.PHONY : src/fortran-4c/racdi.s

# target to generate assembly for a file
src/fortran-4c/racdi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/racdi.c.s
.PHONY : src/fortran-4c/racdi.c.s

src/fortran-4c/sdbar42_lrzv.o: src/fortran-4c/sdbar42_lrzv.c.o
.PHONY : src/fortran-4c/sdbar42_lrzv.o

# target to build an object file
src/fortran-4c/sdbar42_lrzv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/sdbar42_lrzv.c.o
.PHONY : src/fortran-4c/sdbar42_lrzv.c.o

src/fortran-4c/sdbar42_lrzv.i: src/fortran-4c/sdbar42_lrzv.c.i
.PHONY : src/fortran-4c/sdbar42_lrzv.i

# target to preprocess a source file
src/fortran-4c/sdbar42_lrzv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/sdbar42_lrzv.c.i
.PHONY : src/fortran-4c/sdbar42_lrzv.c.i

src/fortran-4c/sdbar42_lrzv.s: src/fortran-4c/sdbar42_lrzv.c.s
.PHONY : src/fortran-4c/sdbar42_lrzv.s

# target to generate assembly for a file
src/fortran-4c/sdbar42_lrzv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/sdbar42_lrzv.c.s
.PHONY : src/fortran-4c/sdbar42_lrzv.c.s

src/fortran-4c/sinf42.o: src/fortran-4c/sinf42.c.o
.PHONY : src/fortran-4c/sinf42.o

# target to build an object file
src/fortran-4c/sinf42.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/sinf42.c.o
.PHONY : src/fortran-4c/sinf42.c.o

src/fortran-4c/sinf42.i: src/fortran-4c/sinf42.c.i
.PHONY : src/fortran-4c/sinf42.i

# target to preprocess a source file
src/fortran-4c/sinf42.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/sinf42.c.i
.PHONY : src/fortran-4c/sinf42.c.i

src/fortran-4c/sinf42.s: src/fortran-4c/sinf42.c.s
.PHONY : src/fortran-4c/sinf42.s

# target to generate assembly for a file
src/fortran-4c/sinf42.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/sinf42.c.s
.PHONY : src/fortran-4c/sinf42.c.s

src/fortran-4c/vcoord.o: src/fortran-4c/vcoord.c.o
.PHONY : src/fortran-4c/vcoord.o

# target to build an object file
src/fortran-4c/vcoord.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/vcoord.c.o
.PHONY : src/fortran-4c/vcoord.c.o

src/fortran-4c/vcoord.i: src/fortran-4c/vcoord.c.i
.PHONY : src/fortran-4c/vcoord.i

# target to preprocess a source file
src/fortran-4c/vcoord.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/vcoord.c.i
.PHONY : src/fortran-4c/vcoord.c.i

src/fortran-4c/vcoord.s: src/fortran-4c/vcoord.c.s
.PHONY : src/fortran-4c/vcoord.s

# target to generate assembly for a file
src/fortran-4c/vcoord.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/vcoord.c.s
.PHONY : src/fortran-4c/vcoord.c.s

src/fortran-4c/vharmonique.o: src/fortran-4c/vharmonique.c.o
.PHONY : src/fortran-4c/vharmonique.o

# target to build an object file
src/fortran-4c/vharmonique.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/vharmonique.c.o
.PHONY : src/fortran-4c/vharmonique.c.o

src/fortran-4c/vharmonique.i: src/fortran-4c/vharmonique.c.i
.PHONY : src/fortran-4c/vharmonique.i

# target to preprocess a source file
src/fortran-4c/vharmonique.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/vharmonique.c.i
.PHONY : src/fortran-4c/vharmonique.c.i

src/fortran-4c/vharmonique.s: src/fortran-4c/vharmonique.c.s
.PHONY : src/fortran-4c/vharmonique.s

# target to generate assembly for a file
src/fortran-4c/vharmonique.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/vharmonique.c.s
.PHONY : src/fortran-4c/vharmonique.c.s

src/fortran-4c/zero_bsj.o: src/fortran-4c/zero_bsj.c.o
.PHONY : src/fortran-4c/zero_bsj.o

# target to build an object file
src/fortran-4c/zero_bsj.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/zero_bsj.c.o
.PHONY : src/fortran-4c/zero_bsj.c.o

src/fortran-4c/zero_bsj.i: src/fortran-4c/zero_bsj.c.i
.PHONY : src/fortran-4c/zero_bsj.i

# target to preprocess a source file
src/fortran-4c/zero_bsj.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/zero_bsj.c.i
.PHONY : src/fortran-4c/zero_bsj.c.i

src/fortran-4c/zero_bsj.s: src/fortran-4c/zero_bsj.c.s
.PHONY : src/fortran-4c/zero_bsj.s

# target to generate assembly for a file
src/fortran-4c/zero_bsj.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/fortran-4c/zero_bsj.c.s
.PHONY : src/fortran-4c/zero_bsj.c.s

src/gaunt.o: src/gaunt.cpp.o
.PHONY : src/gaunt.o

# target to build an object file
src/gaunt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/gaunt.cpp.o
.PHONY : src/gaunt.cpp.o

src/gaunt.i: src/gaunt.cpp.i
.PHONY : src/gaunt.i

# target to preprocess a source file
src/gaunt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/gaunt.cpp.i
.PHONY : src/gaunt.cpp.i

src/gaunt.s: src/gaunt.cpp.s
.PHONY : src/gaunt.s

# target to generate assembly for a file
src/gaunt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/gaunt.cpp.s
.PHONY : src/gaunt.cpp.s

src/homeier.o: src/homeier.cpp.o
.PHONY : src/homeier.o

# target to build an object file
src/homeier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/homeier.cpp.o
.PHONY : src/homeier.cpp.o

src/homeier.i: src/homeier.cpp.i
.PHONY : src/homeier.i

# target to preprocess a source file
src/homeier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/homeier.cpp.i
.PHONY : src/homeier.cpp.i

src/homeier.s: src/homeier.cpp.s
.PHONY : src/homeier.s

# target to generate assembly for a file
src/homeier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/homeier.cpp.s
.PHONY : src/homeier.cpp.s

src/libslater.o: src/libslater.cpp.o
.PHONY : src/libslater.o

# target to build an object file
src/libslater.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/libslater.cpp.o
.PHONY : src/libslater.cpp.o

src/libslater.i: src/libslater.cpp.i
.PHONY : src/libslater.i

# target to preprocess a source file
src/libslater.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/libslater.cpp.i
.PHONY : src/libslater.cpp.i

src/libslater.s: src/libslater.cpp.s
.PHONY : src/libslater.s

# target to generate assembly for a file
src/libslater.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/libslater.cpp.s
.PHONY : src/libslater.cpp.s

src/logger.o: src/logger.cpp.o
.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/nested_summation.o: src/nested_summation.cpp.o
.PHONY : src/nested_summation.o

# target to build an object file
src/nested_summation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/nested_summation.cpp.o
.PHONY : src/nested_summation.cpp.o

src/nested_summation.i: src/nested_summation.cpp.i
.PHONY : src/nested_summation.i

# target to preprocess a source file
src/nested_summation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/nested_summation.cpp.i
.PHONY : src/nested_summation.cpp.i

src/nested_summation.s: src/nested_summation.cpp.s
.PHONY : src/nested_summation.s

# target to generate assembly for a file
src/nested_summation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/nested_summation.cpp.s
.PHONY : src/nested_summation.cpp.s

src/parameters.o: src/parameters.cpp.o
.PHONY : src/parameters.o

# target to build an object file
src/parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/parameters.cpp.o
.PHONY : src/parameters.cpp.o

src/parameters.i: src/parameters.cpp.i
.PHONY : src/parameters.i

# target to preprocess a source file
src/parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/parameters.cpp.i
.PHONY : src/parameters.cpp.i

src/parameters.s: src/parameters.cpp.s
.PHONY : src/parameters.s

# target to generate assembly for a file
src/parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/parameters.cpp.s
.PHONY : src/parameters.cpp.s

src/safouhi-4c.o: src/safouhi-4c.cpp.o
.PHONY : src/safouhi-4c.o

# target to build an object file
src/safouhi-4c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/safouhi-4c.cpp.o
.PHONY : src/safouhi-4c.cpp.o

src/safouhi-4c.i: src/safouhi-4c.cpp.i
.PHONY : src/safouhi-4c.i

# target to preprocess a source file
src/safouhi-4c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/safouhi-4c.cpp.i
.PHONY : src/safouhi-4c.cpp.i

src/safouhi-4c.s: src/safouhi-4c.cpp.s
.PHONY : src/safouhi-4c.s

# target to generate assembly for a file
src/safouhi-4c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/safouhi-4c.cpp.s
.PHONY : src/safouhi-4c.cpp.s

src/semi-infinite-3c.o: src/semi-infinite-3c.cpp.o
.PHONY : src/semi-infinite-3c.o

# target to build an object file
src/semi-infinite-3c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/semi-infinite-3c.cpp.o
.PHONY : src/semi-infinite-3c.cpp.o

src/semi-infinite-3c.i: src/semi-infinite-3c.cpp.i
.PHONY : src/semi-infinite-3c.i

# target to preprocess a source file
src/semi-infinite-3c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/semi-infinite-3c.cpp.i
.PHONY : src/semi-infinite-3c.cpp.i

src/semi-infinite-3c.s: src/semi-infinite-3c.cpp.s
.PHONY : src/semi-infinite-3c.s

# target to generate assembly for a file
src/semi-infinite-3c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/semi-infinite-3c.cpp.s
.PHONY : src/semi-infinite-3c.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libslater.dir/build.make CMakeFiles/libslater.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... cleancov"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... libslater"
	@echo "... simple"
	@echo "... simple2"
	@echo "... simple3"
	@echo "... simple4c"
	@echo "... simple4c_any"
	@echo "... test-all"
	@echo "... test-sph-harm"
	@echo "... test3c"
	@echo "... test4c"
	@echo "... examples/simple.o"
	@echo "... examples/simple.i"
	@echo "... examples/simple.s"
	@echo "... examples/simple2.o"
	@echo "... examples/simple2.i"
	@echo "... examples/simple2.s"
	@echo "... examples/simple3.o"
	@echo "... examples/simple3.i"
	@echo "... examples/simple3.s"
	@echo "... examples/simple4c.o"
	@echo "... examples/simple4c.i"
	@echo "... examples/simple4c.s"
	@echo "... examples/simple4c_any.o"
	@echo "... examples/simple4c_any.i"
	@echo "... examples/simple4c_any.s"
	@echo "... examples/test-sph-harm.o"
	@echo "... examples/test-sph-harm.i"
	@echo "... examples/test-sph-harm.s"
	@echo "... examples/test3c.o"
	@echo "... examples/test3c.i"
	@echo "... examples/test3c.s"
	@echo "... examples/test4c.o"
	@echo "... examples/test4c.i"
	@echo "... examples/test4c.s"
	@echo "... precalculate/gaunt-table.o"
	@echo "... precalculate/gaunt-table.i"
	@echo "... precalculate/gaunt-table.s"
	@echo "... src/analytical-3c.o"
	@echo "... src/analytical-3c.i"
	@echo "... src/analytical-3c.s"
	@echo "... src/basis_functions.o"
	@echo "... src/basis_functions.i"
	@echo "... src/basis_functions.s"
	@echo "... src/bfunctions.o"
	@echo "... src/bfunctions.i"
	@echo "... src/bfunctions.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/fortran-4c/DFj42.o"
	@echo "... src/fortran-4c/DFj42.i"
	@echo "... src/fortran-4c/DFj42.s"
	@echo "... src/fortran-4c/DG.o"
	@echo "... src/fortran-4c/DG.i"
	@echo "... src/fortran-4c/DG.s"
	@echo "... src/fortran-4c/DX.o"
	@echo "... src/fortran-4c/DX.i"
	@echo "... src/fortran-4c/DX.s"
	@echo "... src/fortran-4c/Dbsj.o"
	@echo "... src/fortran-4c/Dbsj.i"
	@echo "... src/fortran-4c/Dbsj.s"
	@echo "... src/fortran-4c/Dtk.o"
	@echo "... src/fortran-4c/Dtk.i"
	@echo "... src/fortran-4c/Dtk.s"
	@echo "... src/fortran-4c/FSCj.o"
	@echo "... src/fortran-4c/FSCj.i"
	@echo "... src/fortran-4c/FSCj.s"
	@echo "... src/fortran-4c/Fj42.o"
	@echo "... src/fortran-4c/Fj42.i"
	@echo "... src/fortran-4c/Fj42.s"
	@echo "... src/fortran-4c/GREP-WD42.o"
	@echo "... src/fortran-4c/GREP-WD42.i"
	@echo "... src/fortran-4c/GREP-WD42.s"
	@echo "... src/fortran-4c/GaussLag.o"
	@echo "... src/fortran-4c/GaussLag.i"
	@echo "... src/fortran-4c/GaussLag.s"
	@echo "... src/fortran-4c/GaussLeg.o"
	@echo "... src/fortran-4c/GaussLeg.i"
	@echo "... src/fortran-4c/GaussLeg.s"
	@echo "... src/fortran-4c/HFa42.o"
	@echo "... src/fortran-4c/HFa42.i"
	@echo "... src/fortran-4c/HFa42.s"
	@echo "... src/fortran-4c/HFj42.o"
	@echo "... src/fortran-4c/HFj42.i"
	@echo "... src/fortran-4c/HFj42.s"
	@echo "... src/fortran-4c/LU.o"
	@echo "... src/fortran-4c/LU.i"
	@echo "... src/fortran-4c/LU.s"
	@echo "... src/fortran-4c/bessel_reduite.o"
	@echo "... src/fortran-4c/bessel_reduite.i"
	@echo "... src/fortran-4c/bessel_reduite.s"
	@echo "... src/fortran-4c/calf42.o"
	@echo "... src/fortran-4c/calf42.i"
	@echo "... src/fortran-4c/calf42.s"
	@echo "... src/fortran-4c/cartco.o"
	@echo "... src/fortran-4c/cartco.i"
	@echo "... src/fortran-4c/cartco.s"
	@echo "... src/fortran-4c/coeffbons.o"
	@echo "... src/fortran-4c/coeffbons.i"
	@echo "... src/fortran-4c/coeffbons.s"
	@echo "... src/fortran-4c/constlmp.o"
	@echo "... src/fortran-4c/constlmp.i"
	@echo "... src/fortran-4c/constlmp.s"
	@echo "... src/fortran-4c/dobin.o"
	@echo "... src/fortran-4c/dobin.i"
	@echo "... src/fortran-4c/dobin.s"
	@echo "... src/fortran-4c/fa42.o"
	@echo "... src/fortran-4c/fa42.i"
	@echo "... src/fortran-4c/fa42.s"
	@echo "... src/fortran-4c/g.o"
	@echo "... src/fortran-4c/g.i"
	@echo "... src/fortran-4c/g.s"
	@echo "... src/fortran-4c/gaunt.o"
	@echo "... src/fortran-4c/gaunt.i"
	@echo "... src/fortran-4c/gaunt.s"
	@echo "... src/fortran-4c/gaunt1.o"
	@echo "... src/fortran-4c/gaunt1.i"
	@echo "... src/fortran-4c/gaunt1.s"
	@echo "... src/fortran-4c/harmonique.o"
	@echo "... src/fortran-4c/harmonique.i"
	@echo "... src/fortran-4c/harmonique.s"
	@echo "... src/fortran-4c/hatk.o"
	@echo "... src/fortran-4c/hatk.i"
	@echo "... src/fortran-4c/hatk.s"
	@echo "... src/fortran-4c/legendre.o"
	@echo "... src/fortran-4c/legendre.i"
	@echo "... src/fortran-4c/legendre.s"
	@echo "... src/fortran-4c/main.o"
	@echo "... src/fortran-4c/main.i"
	@echo "... src/fortran-4c/main.s"
	@echo "... src/fortran-4c/miscfunc.o"
	@echo "... src/fortran-4c/miscfunc.i"
	@echo "... src/fortran-4c/miscfunc.s"
	@echo "... src/fortran-4c/msphj.o"
	@echo "... src/fortran-4c/msphj.i"
	@echo "... src/fortran-4c/msphj.s"
	@echo "... src/fortran-4c/power_x.o"
	@echo "... src/fortran-4c/power_x.i"
	@echo "... src/fortran-4c/power_x.s"
	@echo "... src/fortran-4c/racdi.o"
	@echo "... src/fortran-4c/racdi.i"
	@echo "... src/fortran-4c/racdi.s"
	@echo "... src/fortran-4c/sdbar42_lrzv.o"
	@echo "... src/fortran-4c/sdbar42_lrzv.i"
	@echo "... src/fortran-4c/sdbar42_lrzv.s"
	@echo "... src/fortran-4c/sinf42.o"
	@echo "... src/fortran-4c/sinf42.i"
	@echo "... src/fortran-4c/sinf42.s"
	@echo "... src/fortran-4c/vcoord.o"
	@echo "... src/fortran-4c/vcoord.i"
	@echo "... src/fortran-4c/vcoord.s"
	@echo "... src/fortran-4c/vharmonique.o"
	@echo "... src/fortran-4c/vharmonique.i"
	@echo "... src/fortran-4c/vharmonique.s"
	@echo "... src/fortran-4c/zero_bsj.o"
	@echo "... src/fortran-4c/zero_bsj.i"
	@echo "... src/fortran-4c/zero_bsj.s"
	@echo "... src/gaunt.o"
	@echo "... src/gaunt.i"
	@echo "... src/gaunt.s"
	@echo "... src/homeier.o"
	@echo "... src/homeier.i"
	@echo "... src/homeier.s"
	@echo "... src/libslater.o"
	@echo "... src/libslater.i"
	@echo "... src/libslater.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/nested_summation.o"
	@echo "... src/nested_summation.i"
	@echo "... src/nested_summation.s"
	@echo "... src/parameters.o"
	@echo "... src/parameters.i"
	@echo "... src/parameters.s"
	@echo "... src/safouhi-4c.o"
	@echo "... src/safouhi-4c.i"
	@echo "... src/safouhi-4c.s"
	@echo "... src/semi-infinite-3c.o"
	@echo "... src/semi-infinite-3c.i"
	@echo "... src/semi-infinite-3c.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

